spring:
  application:
    name: SpringbootDemo
  datasource:
    username: visitor
    password: mysql@irbl
    url: jdbc:mysql://101.132.253.222:3306/seiii
    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
    schema: classpath:schema.sql
    data: classpath:data.sql
#    在Spring2:x版本中需加上此行6:
    initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8090

### MULTIPART (MultipartProperties)
## 开启 multipart 上传功能
#spring.servlet.multipart.enabled=true
## 文件写入磁盘的阈值
#spring.servlet.multipart.file-size-threshold=2KB
## 最大文件大小
#spring.servlet.multipart.max-file-size=200MB
## 最大请求大小
#spring.servlet.multipart.max-request-size=215MB
### 文件存储所需参数
## 所有通过 REST APIs 上传的文件都将存储在此目录下
#file.upload-dir=./uploads